language: php
php: 7.1
before_script:
- rm composer.lock
- composer install --no-progress --no-interaction --prefer-dist --no-suggest --no-dev
- composer update --no-scripts
- php artisan config:cache
- cp .env.travis .env
- mysql -e 'create database homestead_test;'
script:
- vendor/bin/phpunit
notifications:
  email:
    recipients:
    - lambot.rom@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: TrWXHYNayQf7HJhKKSYva1fHcgiIkyxty1EKxG6n7t2whWnZRFmzTnbr8iCIKxX24u2l/L9rovxO+WX5C3oM98EeWN9TwR3PhIUrBrWuQu223+vkejwHkRRFDirlQnF3OWdMYXlJ0PHz10P8Ko48DIyFhXPeMF6Rr5ba6+C5Pm8V5qtR+N/AOCPhWfZZrlZMtwMuFa3ablW0c+yu0RPj1yyQZP6OD0rt/pJpyKWFri/g4BuQfMmgLSv/atW5DSIW8chGfQnm/oW+EYWUjgSRyHtiSny+l1f8GTaWmaLWn1Y6f2K5LdIGwYS2Oj3PmiGre3dJTrC8zalpQyxJuGXfom6N9aX7/oJ6vtgU0/RYrAfNwornHuM0OF1oJFpwIRhdAIUDRSIYUyg1Hia6ghrbHoxTXE/l/x1ZX4TFFLv3aNAXAx/kRulUvqJNYuTqFXNzFs7xvYRCBvoYmql0GW/ztKtdgVp9+Bi5vi8io5u91eVbmZMnNVn33DwHwGmImfE5sZV9T2D5NFowlObKssj8nhUMZM46Xe9PFORXNLWMWUpPlhc8P8UtZKlgogHFH/ts/ezKwR7PaydYIMKlEDvdqh4maEZdQ+dlvvqmvYtgrs4GYb7ztAp8CZjUdGSo0KzmHfQzcKfNT504k6huEBhT5NlaZuyEhJpZYioGs12J2s4=
  app: limitless-springs-83583
  on:
    repo: esgiprojetninja/devAwayApi
